server/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pdado/', include('probdado.urls')),
]

server/probdado/urls.py
from django.urls import path, re_path, include, register_converter

from django.views.generic import TemplateView

from . import views

app_name = 'probdado'

urlpatterns = [
    #~ path('', views.Main.as_view(), name='main'),
    path('rodada/<int:pk>/', views.View_Rodada.as_view(), name='rodada'),
    path('revelar/<int:rodada_pk>/', views.View_Revelar.as_view(), name='revelar'),
    path('novarodada/<int:match_pk>/', views.View_NovaRodada.as_view(), name='novarodada'),
    path('novacombinacao/<int:room_pk>/', views.View_NovaCombinacao.as_view(), name='novacombinacao'),
]

server/core/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

from core import utils

class User(AbstractUser):
    pass
    # add additional fields in here

    def __str__(self):
        return self.username


class Game(models.Model):
    name = models.CharField(max_length=64)
    app = models.CharField(max_length=32)
    max_players = models.IntegerField(default=4)

    def __str__(self):
        return "{name} ({app}): {mp}".format(name = self.name, app = self.app, mp = self.max_players)


class Room(models.Model):
    owner    = models.ForeignKey(User, on_delete=models.CASCADE)
    code     = models.CharField(max_length=16)  # (64 + 8) / 5 = 14.4
    active   = models.BooleanField(default=True)

    def create_room(self, game, owner):
        pass

    def __str__(self):
        return self.code


class Player(models.Model):
    # YKL: check how to do it with sessions! Add name
    room = models.ManyToManyField(Room)
    active   = models.BooleanField(default=True)


class Match(models.Model):
    room   = models.ForeignKey(Room, on_delete=models.CASCADE)
    game   = models.ForeignKey(Game, on_delete=models.CASCADE)
    active = models.BooleanField(default=True)

    def __str__(self):
        return "{gm}: {rc}".format(gm = self.game.name, rc = self.room.code)


class Score(models.Model):
    match  = models.ForeignKey(Match, on_delete=models.CASCADE)
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    score  = models.IntegerField(default=0)

server/probdado/models.py
from django.db import models

# Create your models here.
class Combinacao(models.Model):
    dado1 = models.IntegerField()
    dado2 = models.IntegerField()
#    CorDado1 = models.CharField(max_length=10)
#    CorDado2 = models.CharField(max_length=10)

    def __str__(self):
        return "{d1} - {d2}".format(d1 = self.dado1, d2 = self.dado2)

class Dica(models.Model):
    text = models.CharField(max_length=256)
    combinacoes = models.ManyToManyField(Combinacao)

    def __str__(self):
        return self.text

# ------------------------------------------------------------------------------

class Partida(models.Model):
    match = models.OneToOneField('core.Match', on_delete=models.CASCADE, primary_key=True)
    combinacao = models.ForeignKey(Combinacao, on_delete=models.CASCADE)

    def __str__(self):
        return "{match}: {combinacao}".format(match = self.match, combinacao=self.combinacao)

class Rodada(models.Model):
    partida = models.ForeignKey(Partida, on_delete=models.CASCADE)
    dica    = models.ForeignKey(Dica, on_delete=models.CASCADE)
    estado  = models.IntegerField(default=0)  # máquina de estado: 0:aceitando alternativas (respostas) dos players, 1:feedback, 2:encerrado

    def __str__(self):
        return "{d} - {e}".format(d=self.dica, e=self.estado)

class Alternativa(models.Model):
    rodada  = models.ForeignKey(Rodada, on_delete=models.CASCADE)
    texto   = models.TextField(max_length=64)
    correta = models.BooleanField(default=False)
    ponto   = models.IntegerField()  # Regra de negócio: probabilidade 10 pontos, combinação 50 pontos, combinação errada -10 pontos

class Resposta(models.Model):
    # Regra de negócio: Protect against multiple selection during the same "Rodada" -- code this rule.
    player      = models.ForeignKey('core.Player', on_delete=models.CASCADE)
    alternativa = models.ForeignKey(Alternativa, on_delete=models.CASCADE)

server/sc/models.py
from django.db import models

# Create your models here.

server/probdado/views.py
import random

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.forms.models import model_to_dict
from django.urls import reverse
from django.db.models import Q

from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from django.views import View
from django.views.generic import TemplateView, ListView, DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from .models import Combinacao, Dica, Partida, Rodada, Alternativa, Resposta
from core.models import Game, Room, Match

# Create your views here.

class Main(TemplateView):
    template_name = 'probdado/main.bkp.html'

class View_Rodada(DetailView):
    template_name = 'probdado/main.html'
    model = Rodada

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()  # rodada
        context = self.get_context_data()
        return self.render_to_response(context)


class View_Revelar(View):
    def get(self, request, *args, **kwargs):
        rodada_pk = self.kwargs.get('rodada_pk')
        rodada = Rodada.objects.filter(pk=rodada_pk).get()
        rodada.estado = 1
        rodada.save()

        url = reverse('probdado:rodada', kwargs={'pk': rodada.pk})
        return HttpResponseRedirect(url)



class View_NovaCombinacao(View):
    def get(self, request, *args, **kwargs):
        game = Game.objects.filter(app='probdado').get()

        room_pk = self.kwargs.get('room_pk')
        room = Room.objects.filter(pk=room_pk).get()

        # TODO? provavelmente não: por enquanto pode selecionar combinação já usada nesta sala: Mas não é necessariamente um problema!
        offset = random.randint(0, 35)
        combinacao = Combinacao.objects.all()[offset:offset+1].get()

        match = Match(game=game, room=room, active=True)
        match.save()

        partida = Partida(match=match, combinacao=combinacao)
        partida.save()

        dicas = combinacao.dica_set.all()
        num_dicas = dicas.count()

        offset = random.randint(0, num_dicas-1)
        dica = Dica.objects.all()[offset:offset+1].get()

        rodada = Rodada(partida=partida, dica=dica, estado=0)
        rodada.save()

        # TODO Criar alternativas

        url = reverse('probdado:rodada', kwargs={'pk': rodada.pk})
        return HttpResponseRedirect(url)


class View_NovaRodada(View):
    def get(self, request, *args, **kwargs):
        match_pk = self.kwargs.get('match_pk')
        match = Match.objects.filter(pk=match_pk).get()

        partida = Partida.objects.filter(match=match).get()

        partida.rodada_set.update(estado=2)

        combinacao = partida.combinacao
        dicas = combinacao.dica_set.all()
        num_dicas = dicas.count()

        # TODO?: por enquanto pode selecionar dica já usada por esta combinação nesta sala: Problema? Talvez não.
        offset = random.randint(0, num_dicas-1)
        dica = Dica.objects.all()[offset:offset+1].get()

        rodada = Rodada(partida=partida, dica=dica, estado=0)
        rodada.save()

        # TODO Criar alternativas

        url = reverse('probdado:rodada', kwargs={'pk': rodada.pk})
        return HttpResponseRedirect(url)

server/sc/views.py
from django.shortcuts import render

# Create your views here.

server/core/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Webgames{% endblock %}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
  {% block head %}

  {% endblock %}
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">GreenFoods</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        {% if user.is_authenticated %}

        {% else %}
          <p>You are not logged in</p>
          <a class="nav-link" href="TODO">Log In</a>
          <a class="nav-link" href="TODO">Sign Up</a>
           <form class="d-flex" method="post">
            <tr>
              <th>{% csrf_token %}</th>
              <td>{{ form.as_p }}</td>
              <td><button class="btn btn-outline-success" type="submit">Log In</button></td>
            </tr>
          </form>
        {% endif %}
        <a class="nav-link active" aria-current="page" href="#">Home</a>
        <a class="nav-link" href="#">Pricing</a>
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Ola, {{ user.username }}
          </button>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="TODO">Log Out</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</nav>
  <main>
    <div class="container text-center pt-3">
          {% block content %}
          {% endblock %}
    </div>
  </main>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>

server/probdado/templates/probdado/main.bkp0.html
{% extends "base.html" %}

{% block head %}
    <title>Canvas - jogo</title>
    <meta charset="UTF-8"/>
    <meta name="viewpoint" content= "widht=device-width", initial-scale=1.0"/>
    <script type="text/javascript">
        function desenha(){
            var canvas=document.getElementById("desenho")
            var ctx=canvas.getContext('2d')

            //colorir bordas pretas
            ctx.fillStyle="#000"
                ctx.fillRect(0,0,500,5)
                ctx.fillRect(0,495,500,500)
                ctx.fillRect(0,0,5,500)
                ctx.fillRect(495,0,500,500)


            //colorir retangulos vermelhos
            ctx.fillStyle="#f00"
                ctx.fillRect(75,75,70,70)
                ctx.fillRect(145,145,70,70)
                ctx.fillRect(215,215,70,70)
                ctx.fillRect(285,285,70,70)
                ctx.fillRect(355,355,70,70)
                ctx.fillRect(425,425,70,70)
                ctx.fillRect(425,75,70,70)
                ctx.fillRect(355,145,70,70)
                ctx.fillRect(285,215,70,70)
                ctx.fillRect(215,285,70,70)
                ctx.fillRect(145,355,70,70)
                ctx.fillRect(75,425,70,70)

            //colorir retangulos azuis
            ctx.fillStyle="#00f"
                ctx.fillRect(145,75,70,70)
                ctx.fillRect(145,215,70,70)
                ctx.fillRect(145,285,70,70)
                ctx.fillRect(145,425,70,70)

                ctx.fillRect(355,75,70,70)
                ctx.fillRect(355,215,70,70)
                ctx.fillRect(355,285,70,70)
                ctx.fillRect(355,425,70,70)

                ctx.fillRect(75,145,70,70)
                ctx.fillRect(215,145,70,70)
                ctx.fillRect(285,145,70,70)
                ctx.fillRect(425,145,70,70)

                ctx.fillRect(75,355,70,70)
                ctx.fillRect(215,355,70,70)
                ctx.fillRect(285,355,70,70)
                ctx.fillRect(425,355,70,70)
                ctx.fill()

            //colorir retangulos verdes
            ctx.fillStyle="#0f0"
                ctx.fillRect(215,75,70,70)
                ctx.fillRect(285,75,70,70)
                ctx.fillRect(425,215,70,70)
                ctx.fillRect(425,285,70,70)

                ctx.fillRect(75,215,70,70)
                ctx.fillRect(75,285,70,70)
                ctx.fillRect(215,425,70,70)
                ctx.fillRect(285,425,70,70)
            ctx.fill()

            //inserindo o texto azul
            ctx.fillStyle="blue";
            ctx.font = "bold 36px sans-serif"
                ctx.fillText("1",100,50)
                ctx.fillText("2",30,190)
                ctx.fillText("3",240,50)
                ctx.fillText("4",30,330)
                ctx.fillText("5",380,50)
                ctx.fillText("6",30,470)
            ctx.fill()

            //inserindo o texto vermelho
            ctx.fillStyle="red"
            ctx.font = "bold 36px sans-serif"
                ctx.fillText("1",30,120)
                ctx.fillText("2",170,50)
                ctx.fillText("3",30,260)
                ctx.fillText("4",310,50)
                ctx.fillText("5",30,400)
                ctx.fillText("6",450,50)
            ctx.fill()

            //inserindo o texto preto
            ctx.fillStyle="black"
                ctx.font= "bold 80px sans-serif"
                ctx.fillText("Q2",125,205)
                ctx.fillText("Q1",330,205)
                ctx.fillText("Q3",125,415)
                ctx.fillText("Q4",330,415)
            ctx.fill()

            //linha diagonal
            ctx.moveTo(5,5)
            ctx.lineTo(75,75)
            ctx.stroke()

            //linas horizontais
            ctx.moveTo(5,5)
            ctx.lineTo(495,5)
            ctx.stroke()

            ctx.moveTo(5,75)
            ctx.lineTo(495,75)
            ctx.stroke()

            ctx.moveTo(5,145)
            ctx.lineTo(495,145)
            ctx.stroke()

            ctx.moveTo(5,215)
            ctx.lineTo(495,215)
            ctx.stroke()

            ctx.moveTo(5,285)
            ctx.lineTo(495,285)
            ctx.stroke()

            ctx.moveTo(5,355)
            ctx.lineTo(495,355)
            ctx.stroke()

            ctx.moveTo(5,425)
            ctx.lineTo(495, 425)
            ctx.stroke()

            ctx.moveTo(5,495)
            ctx.lineTo(495, 495)
            ctx.stroke()

            ctx.moveTo(5,75)
            ctx.lineTo(495,75)
            ctx.stroke()

            //linhas verticais
            ctx.moveTo(5,5)
            ctx.lineTo(5,495)
            ctx.stroke()

            ctx.moveTo(75,5)
            ctx.lineTo(75,495)
            ctx.stroke()

            ctx.moveTo(145,5)
            ctx.lineTo(145,495)
            ctx.stroke()

            ctx.moveTo(215,5)
            ctx.lineTo(215,495)
            ctx.stroke()

            ctx.moveTo(285,5)
            ctx.lineTo(285,495)
            ctx.stroke()

            ctx.moveTo(355,5)
            ctx.lineTo(355,495)
            ctx.stroke()

            ctx.moveTo(425,5)
            ctx.lineTo(425,495)
            ctx.stroke()

            ctx.moveTo(495,5)
            ctx.lineTo(495,495)
            ctx.stroke()
        }
        $(function() {
            console.log( "ready!" );
            desenha();
        });
    </script>
{% endblock %}

{% block content %}
    <canvas id="desenho" width="500" height="500" style="border:1px solid #000;">
        <h1> Probabilidado</h1>
    </canvas>
{% endblock %}




server/probdado/templates/probdado/main.bkp1.html
{% extends "base.html" %}

{% block head %}
    <title>Canvas - jogo</title>
    <meta charset="UTF-8"/>
    <meta name="viewpoint" content= "widht=device-width", initial-scale=1.0"/>
    <script type="text/javascript">
        function desenha(){
            var canvas=document.getElementById("desenho")
            var ctx=canvas.getContext('2d')

            //colorir bordas pretas
            ctx.fillStyle="#000"
                ctx.fillRect(0,0,500,5)
                ctx.fillRect(0,495,500,500)
                ctx.fillRect(0,0,5,500)
                ctx.fillRect(495,0,500,500)


            //colorir retangulos vermelhos
            ctx.fillStyle="#f00"
                ctx.fillRect(75,75,70,70)
                ctx.fillRect(145,145,70,70)
                ctx.fillRect(215,215,70,70)
                ctx.fillRect(285,285,70,70)
                ctx.fillRect(355,355,70,70)
                ctx.fillRect(425,425,70,70)
                ctx.fillRect(425,75,70,70)
                ctx.fillRect(355,145,70,70)
                ctx.fillRect(285,215,70,70)
                ctx.fillRect(215,285,70,70)
                ctx.fillRect(145,355,70,70)
                ctx.fillRect(75,425,70,70)

            //colorir retangulos azuis
            ctx.fillStyle="#00f"
                ctx.fillRect(145,75,70,70)
                ctx.fillRect(145,215,70,70)
                ctx.fillRect(145,285,70,70)
                ctx.fillRect(145,425,70,70)

                ctx.fillRect(355,75,70,70)
                ctx.fillRect(355,215,70,70)
                ctx.fillRect(355,285,70,70)
                ctx.fillRect(355,425,70,70)

                ctx.fillRect(75,145,70,70)
                ctx.fillRect(215,145,70,70)
                ctx.fillRect(285,145,70,70)
                ctx.fillRect(425,145,70,70)

                ctx.fillRect(75,355,70,70)
                ctx.fillRect(215,355,70,70)
                ctx.fillRect(285,355,70,70)
                ctx.fillRect(425,355,70,70)
                ctx.fill()

            //colorir retangulos verdes
            ctx.fillStyle="#0f0"
                ctx.fillRect(215,75,70,70)
                ctx.fillRect(285,75,70,70)
                ctx.fillRect(425,215,70,70)
                ctx.fillRect(425,285,70,70)

                ctx.fillRect(75,215,70,70)
                ctx.fillRect(75,285,70,70)
                ctx.fillRect(215,425,70,70)
                ctx.fillRect(285,425,70,70)
            ctx.fill()

            //inserindo o texto azul
            ctx.fillStyle="blue";
            ctx.font = "bold 36px sans-serif"
                ctx.fillText("1",100,50)
                ctx.fillText("2",30,190)
                ctx.fillText("3",240,50)
                ctx.fillText("4",30,330)
                ctx.fillText("5",380,50)
                ctx.fillText("6",30,470)
            ctx.fill()

            //inserindo o texto vermelho
            ctx.fillStyle="red"
            ctx.font = "bold 36px sans-serif"
                ctx.fillText("1",30,120)
                ctx.fillText("2",170,50)
                ctx.fillText("3",30,260)
                ctx.fillText("4",310,50)
                ctx.fillText("5",30,400)
                ctx.fillText("6",450,50)
            ctx.fill()

            //inserindo o texto preto
            ctx.fillStyle="black"
                ctx.font= "bold 80px sans-serif"
                ctx.fillText("Q2",125,205)
                ctx.fillText("Q1",330,205)
                ctx.fillText("Q3",125,415)
                ctx.fillText("Q4",330,415)
            ctx.fill()

            //linha diagonal
            ctx.moveTo(5,5)
            ctx.lineTo(75,75)
            ctx.stroke()

            //linas horizontais
            ctx.moveTo(5,5)
            ctx.lineTo(495,5)
            ctx.stroke()

            ctx.moveTo(5,75)
            ctx.lineTo(495,75)
            ctx.stroke()

            ctx.moveTo(5,145)
            ctx.lineTo(495,145)
            ctx.stroke()

            ctx.moveTo(5,215)
            ctx.lineTo(495,215)
            ctx.stroke()

            ctx.moveTo(5,285)
            ctx.lineTo(495,285)
            ctx.stroke()

            ctx.moveTo(5,355)
            ctx.lineTo(495,355)
            ctx.stroke()

            ctx.moveTo(5,425)
            ctx.lineTo(495, 425)
            ctx.stroke()

            ctx.moveTo(5,495)
            ctx.lineTo(495, 495)
            ctx.stroke()

            ctx.moveTo(5,75)
            ctx.lineTo(495,75)
            ctx.stroke()

            //linhas verticais
            ctx.moveTo(5,5)
            ctx.lineTo(5,495)
            ctx.stroke()

            ctx.moveTo(75,5)
            ctx.lineTo(75,495)
            ctx.stroke()

            ctx.moveTo(145,5)
            ctx.lineTo(145,495)
            ctx.stroke()

            ctx.moveTo(215,5)
            ctx.lineTo(215,495)
            ctx.stroke()

            ctx.moveTo(285,5)
            ctx.lineTo(285,495)
            ctx.stroke()

            ctx.moveTo(355,5)
            ctx.lineTo(355,495)
            ctx.stroke()

            ctx.moveTo(425,5)
            ctx.lineTo(425,495)
            ctx.stroke()

            ctx.moveTo(495,5)
            ctx.lineTo(495,495)
            ctx.stroke()
        }
        $(function() {
            console.log( "ready!" );
            desenha();
        });
    </script>
{% endblock %}

{% block content %}
    <canvas id="desenho" width="500" height="500" style="border:1px solid #000;">
        <h1> Probabilidado</h1>
    </canvas>


    <br /><b>{{object}}</b>
    <br /><b>{{object.combinacao}}</b>
    {% for dica in object.combinacao.dica_set.all %}
        <br />{{dica}}
    {% endfor %}
{% endblock %}




server/probdado/templates/probdado/main.html
{% extends "base.html" %}

{% block head %}
    <title>Canvas - jogo</title>
    <meta charset="UTF-8"/>
    <meta name="viewpoint" content= "widht=device-width", initial-scale=1.0"/>
    <script type="text/javascript">
        function desenha(){
            var canvas=document.getElementById("desenho")
            var ctx=canvas.getContext('2d')

            //colorir bordas pretas
            ctx.fillStyle="#000"
                ctx.fillRect(0,0,500,5)
                ctx.fillRect(0,495,500,500)
                ctx.fillRect(0,0,5,500)
                ctx.fillRect(495,0,500,500)


            //colorir retangulos vermelhos
            ctx.fillStyle="#f00"
                ctx.fillRect(75,75,70,70)
                ctx.fillRect(145,145,70,70)
                ctx.fillRect(215,215,70,70)
                ctx.fillRect(285,285,70,70)
                ctx.fillRect(355,355,70,70)
                ctx.fillRect(425,425,70,70)
                ctx.fillRect(425,75,70,70)
                ctx.fillRect(355,145,70,70)
                ctx.fillRect(285,215,70,70)
                ctx.fillRect(215,285,70,70)
                ctx.fillRect(145,355,70,70)
                ctx.fillRect(75,425,70,70)

            //colorir retangulos azuis
            ctx.fillStyle="#00f"
                ctx.fillRect(145,75,70,70)
                ctx.fillRect(145,215,70,70)
                ctx.fillRect(145,285,70,70)
                ctx.fillRect(145,425,70,70)

                ctx.fillRect(355,75,70,70)
                ctx.fillRect(355,215,70,70)
                ctx.fillRect(355,285,70,70)
                ctx.fillRect(355,425,70,70)

                ctx.fillRect(75,145,70,70)
                ctx.fillRect(215,145,70,70)
                ctx.fillRect(285,145,70,70)
                ctx.fillRect(425,145,70,70)

                ctx.fillRect(75,355,70,70)
                ctx.fillRect(215,355,70,70)
                ctx.fillRect(285,355,70,70)
                ctx.fillRect(425,355,70,70)
                ctx.fill()

            //colorir retangulos verdes
            ctx.fillStyle="#0f0"
                ctx.fillRect(215,75,70,70)
                ctx.fillRect(285,75,70,70)
                ctx.fillRect(425,215,70,70)
                ctx.fillRect(425,285,70,70)

                ctx.fillRect(75,215,70,70)
                ctx.fillRect(75,285,70,70)
                ctx.fillRect(215,425,70,70)
                ctx.fillRect(285,425,70,70)
            ctx.fill()

            //inserindo o texto azul
            ctx.fillStyle="blue";
            ctx.font = "bold 36px sans-serif"
                ctx.fillText("1",100,50)
                ctx.fillText("2",30,190)
                ctx.fillText("3",240,50)
                ctx.fillText("4",30,330)
                ctx.fillText("5",380,50)
                ctx.fillText("6",30,470)
            ctx.fill()

            //inserindo o texto vermelho
            ctx.fillStyle="red"
            ctx.font = "bold 36px sans-serif"
                ctx.fillText("1",30,120)
                ctx.fillText("2",170,50)
                ctx.fillText("3",30,260)
                ctx.fillText("4",310,50)
                ctx.fillText("5",30,400)
                ctx.fillText("6",450,50)
            ctx.fill()

            //inserindo o texto preto
            ctx.fillStyle="black"
                ctx.font= "bold 80px sans-serif"
                ctx.fillText("Q2",125,205)
                ctx.fillText("Q1",330,205)
                ctx.fillText("Q3",125,415)
                ctx.fillText("Q4",330,415)
            ctx.fill()

            //linha diagonal
            ctx.moveTo(5,5)
            ctx.lineTo(75,75)
            ctx.stroke()

            //linas horizontais
            ctx.moveTo(5,5)
            ctx.lineTo(495,5)
            ctx.stroke()

            ctx.moveTo(5,75)
            ctx.lineTo(495,75)
            ctx.stroke()

            ctx.moveTo(5,145)
            ctx.lineTo(495,145)
            ctx.stroke()

            ctx.moveTo(5,215)
            ctx.lineTo(495,215)
            ctx.stroke()

            ctx.moveTo(5,285)
            ctx.lineTo(495,285)
            ctx.stroke()

            ctx.moveTo(5,355)
            ctx.lineTo(495,355)
            ctx.stroke()

            ctx.moveTo(5,425)
            ctx.lineTo(495, 425)
            ctx.stroke()

            ctx.moveTo(5,495)
            ctx.lineTo(495, 495)
            ctx.stroke()

            ctx.moveTo(5,75)
            ctx.lineTo(495,75)
            ctx.stroke()

            //linhas verticais
            ctx.moveTo(5,5)
            ctx.lineTo(5,495)
            ctx.stroke()

            ctx.moveTo(75,5)
            ctx.lineTo(75,495)
            ctx.stroke()

            ctx.moveTo(145,5)
            ctx.lineTo(145,495)
            ctx.stroke()

            ctx.moveTo(215,5)
            ctx.lineTo(215,495)
            ctx.stroke()

            ctx.moveTo(285,5)
            ctx.lineTo(285,495)
            ctx.stroke()

            ctx.moveTo(355,5)
            ctx.lineTo(355,495)
            ctx.stroke()

            ctx.moveTo(425,5)
            ctx.lineTo(425,495)
            ctx.stroke()

            ctx.moveTo(495,5)
            ctx.lineTo(495,495)
            ctx.stroke()
        }
        $(function() {
            console.log( "ready!" );
            desenha();
        });
    </script>
{% endblock %}

{% block content %}
    <canvas id="desenho" width="500" height="500" style="border:1px solid #000;">
        <h1> Probabilidado</h1>
    </canvas>


    <b>TODO: Listar dicas antigas</b>

    <br />Dica: <b>{{rodada.dica}}</b>
    {% for alternativa in rodada.alternativa_set.all %}
        <br />
        {% if rodada.estado == 1 and alternativa.correta %}
            <div class="alert alert-success" role="alert">
        {% else %}
            <div class="alert alert-primary" role="alert">
        {% endif %}

            {{alternativa.texto}}

        </div>
    {% endfor %}

    <br />

    {% if rodada.estado == 0 %}
        <a class="btn btn-success" href="{% url 'probdado:revelar' rodada_pk=rodada.id %}">Revelar >></a>
    {% else %}
        <a class="btn btn-info" href="{% url 'probdado:novarodada' match_pk=rodada.partida.match.id %}">Próxima Dica (Rodada) >></a>

        <a class="btn btn-info" href="{% url 'probdado:novacombinacao' room_pk=rodada.partida.match.room.id %}">Nova Combinação >></a>
    {% endif %}

{% endblock %}


